"""
Script para hacer dump de la base de datos SQLite a formato SQL
Equivalente a: sqlite3 pos_cremeria.db .dump > pos_cremeria.sql
"""
import sqlite3
import os
from datetime import datetime

def dump_database(db_path, output_file=None):
    """Hacer dump de la base de datos a archivo SQL"""
    
    if not os.path.exists(db_path):
        print(f"❌ Base de datos no encontrada: {db_path}")
        return False
    
    if output_file is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_file = f"pos_cremeria_backup_{timestamp}.sql"
    
    print(f"📦 Haciendo dump de: {db_path}")
    print(f"📄 Archivo de salida: {output_file}")
    
    try:
        conn = sqlite3.connect(db_path)
        
        with open(output_file, 'w', encoding='utf-8') as f:
            # Escribir encabezado
            f.write("-- SQLite Database Dump\n")
            f.write(f"-- Database: {db_path}\n")
            f.write(f"-- Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write("-- Generated by dump_db.py\n\n")
            f.write("BEGIN TRANSACTION;\n\n")
            
            # Iterar sobre cada línea del dump
            for line in conn.iterdump():
                f.write(f"{line}\n")
            
            f.write("\nCOMMIT;\n")
        
        conn.close()
        
        # Obtener tamaño del archivo
        size = os.path.getsize(output_file)
        size_kb = size / 1024
        
        print(f"✅ Dump completado exitosamente!")
        print(f"   Tamaño: {size_kb:.2f} KB ({size:,} bytes)")
        print(f"   Archivo: {os.path.abspath(output_file)}")
        
        return True
        
    except Exception as e:
        print(f"❌ Error al hacer dump: {e}")
        return False

def restaurar_database(sql_file, db_path=None):
    """Restaurar base de datos desde archivo SQL"""
    
    if not os.path.exists(sql_file):
        print(f"❌ Archivo SQL no encontrado: {sql_file}")
        return False
    
    if db_path is None:
        db_path = f"pos_cremeria_restored_{datetime.now().strftime('%Y%m%d_%H%M%S')}.db"
    
    print(f"📥 Restaurando desde: {sql_file}")
    print(f"📦 Base de datos destino: {db_path}")
    
    try:
        # Leer el archivo SQL
        with open(sql_file, 'r', encoding='utf-8') as f:
            sql_script = f.read()
        
        # Crear nueva base de datos y ejecutar script
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()
        cursor.executescript(sql_script)
        conn.commit()
        conn.close()
        
        print(f"✅ Base de datos restaurada exitosamente!")
        print(f"   Archivo: {os.path.abspath(db_path)}")
        
        return True
        
    except Exception as e:
        print(f"❌ Error al restaurar: {e}")
        return False

if __name__ == "__main__":
    import sys
    
    print("=" * 70)
    print("🗄️  HERRAMIENTA DE DUMP Y RESTAURACIÓN DE BASE DE DATOS SQLite")
    print("=" * 70)
    
    if len(sys.argv) > 1:
        comando = sys.argv[1].lower()
        
        if comando == "dump":
            db_path = sys.argv[2] if len(sys.argv) > 2 else "pos_cremeria.db"
            output_file = sys.argv[3] if len(sys.argv) > 3 else None
            dump_database(db_path, output_file)
            
        elif comando == "restore" or comando == "restaurar":
            sql_file = sys.argv[2] if len(sys.argv) > 2 else None
            db_path = sys.argv[3] if len(sys.argv) > 3 else None
            
            if sql_file is None:
                print("❌ Debes especificar el archivo SQL a restaurar")
                print("   Uso: python dump_db.py restore archivo.sql [nueva_db.db]")
            else:
                restaurar_database(sql_file, db_path)
        
        else:
            print("❌ Comando no reconocido")
            print("\nComandos disponibles:")
            print("  dump     - Hacer dump de la base de datos")
            print("  restore  - Restaurar desde archivo SQL")
    
    else:
        # Modo interactivo
        print("\n¿Qué deseas hacer?")
        print("1. Hacer dump (backup) de la base de datos")
        print("2. Restaurar base de datos desde SQL")
        print("0. Salir")
        
        opcion = input("\nSelecciona una opción: ").strip()
        
        if opcion == "1":
            db_path = input("Ruta de la base de datos (Enter para 'pos_cremeria.db'): ").strip()
            if not db_path:
                db_path = "pos_cremeria.db"
            
            output = input("Nombre del archivo SQL (Enter para auto-generar): ").strip()
            if not output:
                output = None
            
            dump_database(db_path, output)
            
        elif opcion == "2":
            sql_file = input("Ruta del archivo SQL: ").strip()
            db_path = input("Nombre de la nueva base de datos (Enter para auto-generar): ").strip()
            if not db_path:
                db_path = None
            
            restaurar_database(sql_file, db_path)
            
        elif opcion == "0":
            print("👋 Saliendo...")
        else:
            print("❌ Opción no válida")
    
    print("\n" + "=" * 70)
